config/routes.rb
Rails.application.routes.draw do
  resources :posts
  post '/likes/:post_id', to: 'posts#add_like', as: "add_likes"

  devise_for :users
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  after_save :notify_pusher, on: :create
  belongs_to :post

  def notify_pusher
    Pusher.trigger('post', 'new-like', self.post.serialised)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  # has_attached_file :image
  after_create :notify_pusher
  
  mount_uploader :image, ImageUploader

  validates :caption, presence: true
  # validates_attachment :image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }, size: { in: 0..500.kilobytes }

  def serialised
    {
      id: self.id,
      caption: self.caption,
      user: self.user.username,
      image: self.image_url,
      likes: self.likes[0].like_count
    }
  end

  def notify_pusher
    Pusher.trigger('post', 'new', self.serialised)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc).paginate(page: params[:page], per_page: 5)
  end

  def new
    @post = Post.new
  end

  def create
    @user = User.find(current_user.id)
    @post = @user.posts.new(post_params)
    @post.likes.build()
    
    respond_to do |format|
      if @post.save
        format.json { render :show, status: :created }
      else
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def add_like
    @post = Post.find(params[:post_id])
    if @post
      @post.likes[0].like_count +=1

      if @post.likes[0].save
        respond_to do |format|
          format.json { render :show, status: :ok }
        end
      end
    end
  end

  def add_like
    @post = Post.find(params[:post_id])
    if @post
      @post.likes[0].like_count +=1

      if @post.likes[0].save
        respond_to do |format|
          format.json { render :show, status: :ok }
        end
      end
    end
  end

  private
    def post_params
      params.permit(:caption, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaclone</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <div class="container alert-container col-12 text-center">
        <div class="alert alert-info alert-dismissible fade show" role="alert">
          <p class="notice m-0"><%= notice %></p>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    <% end %>
    <% if alert %>
      <div class="container alert-container col-12 text-center">
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <p class="m-0"><%= alert %></p>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_add_modal.html.erb
<div class="modal fade" id="addPostModal" tabindex="-1" role="dialog" aria-labelledby="addPostModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addPostModalLabel">Add new post</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with(model: @post, format: :json, id: 'add-post') do |form| %>
          <div class="field">
            <%= form.label :caption %>
            <%= form.text_field :caption, id: :caption, class: "form-control" %>
          </div>
          <p class="text-danger upload-error"></p>
          <div class="field">
            <%= form.label :image %>
            <%= form.file_field :image, id: :image, class: "form-control" %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= form.submit 'Add Post', class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_header.html.erb
<header class="bg-info">
  <nav class="navbar navbar-expand-sm navbar-light sticky-top">
  <a class="navbar-brand" href="/">InstaClone</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mobile-menu" aria-controls="mobile-menu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mobile-menu">
      <ul class="navbar-nav mr-auto"></ul>
      <div class="">
        <button class="btn btn-dark"  type="button" data-toggle="modal" data-target="#addPostModal">Add Post</button>
      </div>
    </div>
  </nav>
</header>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<div class="container-fluid bg-light">
  <div class="container p-0">
    <%= render 'header' %>
    <%= render 'add_modal' %>
  </div>
  <div class="container bg-white posts">
    <% @posts.each do |post| %>
      <div class="post-wrapper col-12 col-md-8 col-lg-6 py-2">
        <div class="post-user">
          <h6>@<span class="post-user"><%= post.user.username %></span</h6>
        </div>
        <div class="post">
          <a href="<%= post_path(post) %>">
            <img src="<%= post.image_url %>" class="img-fluid img-thumbnail" />
          </a>
        </div>
        <div class="post-caption">
          <h6 class="mt-2 d-inline-block"><%= post.caption %></h6>
          <%= link_to '', add_likes_path(post_id: post.id), remote: true, method: :post, class: "far fa-heart ml-3 like-icon" %><span class="ml-2" data-post="<%= post.id %>"><%= post.likes[0].like_count %></span>
        </div>
      </div>
    <% end %>
  </div>
  <div class="container">
    <%= will_paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<div class="container">
  <div class="post-wrapper col-12 col-md-8 col-lg-6 py-2">
    <div class="post-user">
      <h6>@<span class="post-user"><%= @post.user.username %></span</h6>
    </div>
    <div class="post">
      <img src="<%= @post.image_url %>" class="img-fluid img-thumbnail" />
    </div>
    <div class="post-caption">
      <h6 class="mt-2 d-inline-block"><%= @post.caption %></h6>
      <%= link_to '', add_likes_path(post_id: @post.id), remote: true, method: :post, class: "far fa-heart ml-3 like-icon" %><span class="ml-2" data-post="<%= @post.id %>"><%= @post.likes[0].like_count %></span>
      <br />
      <%= link_to 'Back', root_path, class: 'btn btn-info' %>
    </div>
  </div>
</div>